version: '3'
services:
    php:
        container_name: php-server-socket
        image: server/php:8-cli-alpine
        build:
            context: ./build
            dockerfile: ./Dockerfile
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./public:/app:ro
        ports:
            - 80:80
            - 12345:12345
        command: >
            sh -c "
                php -q server.php & \
                php -S 0.0.0.0:80
            "
